language: cpp

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
    - os: osx
      osx_image: xcode7.3
      compiler: clang

script:
  - travis_wait if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then .travis/ci_ubuntu14.04.sh ; fi
  - travis_wait if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then .travis/ci_macosx.sh      ; fi
